version: '3'

services:
  DB_postgresql:
    image: postgres:12
    container_name: database
    volumes:
      - database:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - DB_network

  api:
    build: ./python_image
    container_name: python-ping-pong
    restart: always
    networks:
      - DB_network
    depends_on:
      - DB_postgresql
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
  
  nginx:
    build: ./nginx_image
    container_name: nginx-gateway
    restart: always
    ports:
      - "80:80"
    volumes:
    - ./nginx_image/data:/opt
    networks:
      - DB_network
    depends_on:
      - DB_postgresql
      - api
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    


volumes:
  database:
    external: true
    
networks:
  DB_network:
    external: true
