version: '3'

services:
  DB_postgresql:
    image: postgres:12
    container_name: database
    volumes:
      - database:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - DB_network

  api:
    image: voldana/python_ping_pong
    container_name: python_ping_pong
    restart: always
    networks:
      - DB_network
    depends_on:
      - DB_postgresql
  
  nginx:
    image: voldana/custom_nginx
    container_name: nginx_gateway
    restart: always
    ports:
      - "80:80"
    networks:
      - DB_network
    depends_on:
      - DB_postgresql
      - api
    
    


volumes:
  database:
    external: true
    
networks:
  DB_network:
    external: true
