apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx2-pv
  labels:
    type: local
spec:
  storageClassName: nginx
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/data"
