apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: project
  name: nginx2-pvc
  labels:
    app: nginx2
spec:
  storageClassName: nginx
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
